language: es
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  # Text will be processed with case sensitive as default
    "case_sensitive": True
  # use match word boundaries for lookup table
    "use_word_boundaries": True
  - name: RegexEntityExtractor
      # text will be processed with case insensitive as default
    case_sensitive: False
      # use lookup tables to extract entities
    use_lookup_tables: True
      # use regexes to extract entities
    use_regexes: True
      # use match word boundaries for lookup table
    use_word_boundaries: True
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.2

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.2
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
