version: '3'
services:
  rasa:
    container_name: rjb-wwq-rasa-chatbot
    build: ./docker/server
    ports:
      #- 5006:5006
      - 5008:5008
    volumes:
      - .:/app
    command:
      - run
      #- --ssl-certificate
      #- cert.pem
      #- --ssl-keyfile
      #- key.pem
      - -m
      - models
      - --cors
      - "*"
      - --enable-api
      - -p 5008
    depends_on:
      - action-server
  action-server:
    container_name: rjb-wwq-rasa-action
    image: wwq1998/rasa-sdk:3.2.0
    volumes:
      - ./actions:/app/actions
    ports:
      - 5058:5058
    command:
      - start
      - --actions
      - actions
      - -p 5058
