version: '3'
services:
  rasa:
    container_name: rjb-wwq-rasa-chatbot
    build: ./docker/server
    ports:
      #- 5006:5006
      - 5005:5005
    volumes:
      - .:/app
    command:
      - run
      #- --ssl-certificate
      #- cert.pem
      #- --ssl-keyfile
      #- key.pem
      - -m
      - models
      - --cors
      - "*"
      - --enable-api
      - -p 5005
    depends_on:
      - action-server
  action-server:
    container_name: rjb-wwq-rasa-action
    build: ./docker/actions
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055
    command:
      - start
      - --actions
      - actions
      - -p 5055
