version: '3'
services:
  rasa:
    container_name: rjb-wwq-rasa-chatbot
    image: rasa/rasa:3.2.2
    ports:
      #- 5006:5006
      - 5008:5008
    volumes:
      - .:/app
    command:
      - run
      #- --ssl-certificate
      #- ssl.pem
      #- --ssl-keyfile
      #- ssl.key
      - -m
      - models
      - --cors
      - "*"
      - -p 5008
    depends_on:
      - action-server
  action-server:
    container_name: rjb-wwq-rasa-action
    image: wwq1998/rasa-sdk:3.2.0
    volumes:
      - ./actions:/app/actions
    ports:
      - 5058:5058
    command:
      - start
      - --actions
      - actions
      - -p 5058
